LIBBOOTKIT_DIR := src/libbootkit

LIBBOOTKIT_SOURCES = \
	$(LIBBOOTKIT_DIR)/libbootkit.c

LIBBOOTKIT_OBJECTS = $(LIBBOOTKIT_SOURCES:.c=.o)

OBJECTS += $(addprefix $(BUILD_PATH)/, $(LIBBOOTKIT_OBJECTS))

LIBBOOTKIT_COMPILETIME_HEADERS = $(BUILD_PATH)/$(LIBBOOTKIT_DIR)/include

CFLAGS += -I$(LIBBOOTKIT_COMPILETIME_HEADERS)

include $(LIBBOOTKIT_DIR)/payload/rules.mk

PAYLOAD_HEADER = $(LIBBOOTKIT_COMPILETIME_HEADERS)/payload.h
PAYLOAD_NAME = payload

$(PAYLOAD_HEADER): $(PAYLOAD_BIN)
	@$(DIR_HELPER)
	@$(BIN2C) $< $(PAYLOAD_NAME) > $@

libbootkit: $(PAYLOAD_HEADER)
